### ISSUE TITLE
Feature Request: add `--empty` flag to create an empty changeset

### ISSUE THREAD

**Issue by lukebatchelor** [atlassian/changesets#145]
G'day.

We're looking at adding enforcement to PRs that will mean that all PRs must have a changeset. To make this cleaner/more consistent, it would be good if we could create empty changesets to signify "I have *deliberately chosen* to not release a package in this PR.

Happy to make a PR for v1.

**Comment by mitchellhamilton** [comment]
I think this is an interesting idea. [Yarn 2's release stuff has a concept of "declining" a release](https://next.yarnpkg.com/advanced/managing-releases#ensuring-that-versions-are-bumped-ci), I'm not a big fan of that mainly because it would create merge conflicts which is something that changesets manages to avoid and continuing to avoid that would be good. I think the main questions we need to answer for this are:
1. Should we be enforcing that all PRs have changesets or that all PRs have changesets which release or decline to release all changed packages?
1. What should this empty changeset look like? Or maybe an empty changeset is the wrong thing to represent this so more generally, how should declining to release things be represented?
1. Our current advice is "not all PRs have to have changesets." Should we change that advice to "all PRs have to have changesets/all PRs have changesets which release or decline to release all packages" or  "some projects may want to do x, some may want to do y"?

**Comment by lukebatchelor** [comment]
1. Oh, this is an opt in option. It's what the status command was made for. This is just a requirement to be able to use it properly
2. For v1 I'd say an empty release object and a message saying "this changeset *deliberately* does not release anything". Same for V2 but with the new format
3. No no, definitely not. This is just an option for sure. Should be called out _as_ an option, but shouldn't be the default.

**Comment by lukebatchelor** [comment]
Fyi, if it's looks good, we've got an intern starting soon that we might get to tackle this as a good starting issue. 👌

**Comment by Noviny** [comment]
For v1 changeset, I think it's just the arrays for releases and dependents being empty.

For v2 you'd end up with something like:

```
---
---
Empty changeset - made by a pull request where no release was intended.

<User summary>
```

From the CLI perspective, I'm uncertain on whether I want to do `yarn changeset --empty`, or make it an entirely different command. Prompting for a summary still seems fine so I wouldn't mind doing that.

I think if you run `yarn changeset` and select no packages, it should **not** allow you to add an empty changeset, as that feels like an error case

**Comment by lukebatchelor** [comment]
>  think if you run yarn changeset and select no packages, it should not allow you to add an empty changeset, as that feels like an error case

Absolutely.

My vote would be for `--empty` flag and no summary. It feels like a very deliberate action to me, not sure it needs a summary. 
Might also be useful for any scripts creating PRs automatically for example.

**Comment by Noviny** [comment]
> Might also be useful for any scripts creating PRs automatically for example.

Yeah this is probably fine.
