### ISSUE TITLE
get-workspaces: support Lerna (without Yarn), and Pnpm alone

### ISSUE THREAD

**Issue by tunnckoCore** [atlassian/changesets#210]
## Problem

Doesn't support Lerna-non-Yarn-powered and Pnpm monorepos.

## Proposed solution

Pnpm has `pnpm-workspace.yaml` file from which you should get them.
Lerna is possible to run without Yarn, so it will respect its `lerna.packages` field.

It would also be good to include from which "provider" (bolt, lerna, yarn, pnpm) each item comes. 
E.g. `[{ config: pkgJson, provider: <name-or-path-to-file> }]`

Btw, the `config` field isn't exactly a good name for that. Probably it would be better to be renamed to `pkg` because it actually is the path to package.json of each package. But that's for another issue.

Example

```js
[
  { pkg: { name: 'foo-bar' }, type: 'pnpm', config: '/monorepo-root/pnpm-workspace.yaml' },
  { pkg: { name: '@tunnckocore/qux' }, type: 'pnpm', config: '/monorepo-root/pnpm-workspace.yaml' }
  { pkg: { name: '@hela/dev' }, type: 'pnpm', config: '/monorepo-root/pnpm-workspace.yaml' }
]
```

**Comment by Noviny** [comment]
Thanks for raising this!

Pretty much all these changes make sense to me, but are low priority for me (or other core maintainers) go get to. If you'd like to contribute this, I'd be delighted!

Also, quick q: Do you want this just for itself, or do you also want `changesets` to support full lerna + pnpm?

> config

Agree that `config` is the wrong word. We were thinking of switching it to `manifest`, but I think I like `pkg` better.

> type

I'm not sure how relevant it is to have the type on a per-package basis (We'll only ever return one type) - I guess the debate would be whether not wanting this on everything is worth returning an object instead of an array from the whole function, which probably means that this method (adding `type` makes sense - though I wouldn't mind a slightly more descriptive name)

---

A final thing that would probably want to be tackled alongside this is rethinking how we set supported workspace types.

The current option of having `tools: ['yarn', 'bolt', 'root']` is already a pretty crummy API, and also hides that we process these in a fixed order when we're picking from multiple. I don't have a solution in mind, but definitely want to brainstorm one before adding two new types.

One option would be to move it towards an object of:

```js
{
  yarn: true,
  root: false,
  pnpm: true,
}
```

which at least stops the order from looking important.

**Comment by tunnckoCore** [comment]
Agree. I can contribute this week, please assign for easier tracking.

> Do you want this just for itself, or do you also want changesets to support full lerna + pnpm?


Both. I may try `changesets` soon. But for now we need `get-workspaces` in couple of places. :)

**Comment by Andarist** [comment]
> The current option of having tools: ['yarn', 'bolt', 'root'] is already a pretty crummy API, and also hides that we process these in a fixed order when we're picking from multiple. I don't have a solution in mind, but definitely want to brainstorm one before adding two new types.

Is there even a need for `tools` option? Should a caller decide about which kind of workspaces they want to read? Seems like one would always want to read available workspace packages without caring about all possible tools. With the exception of `"root"`.

**Comment by Noviny** [comment]
It can probably be gotten rid of, based on how it's designed to be used. Possibly have an `allowRoot` flag if you want to run a query that will error if there are no workspaces. It would probably be good to know which tool's workspaces it came up with.

The only other use-case is if you have two kinds of specifying workspaces present (bolt and yarn workspaces for example) and you want to force one or the other. We currently have an opaque resolution order.

**Comment by Andarist** [comment]
A type of workspaces could be obtained by a separate exported function (that would be used internally by `getWorkspaces`) - this seems like a less interesting feature (less use cases) so maybe would be good to not include this in default return value.

When (realistically) one would have different type of workspaces in a single working directory?

**Comment by Noviny** [comment]
Just a note, `get-workspaces` has been deprecated in favor of [@manypkg/get-packages
](https://github.com/Thinkmill/manypkg/tree/master/packages/get-packages)

Closing this issue

**Comment by tunnckoCore** [comment]
Thanks for the ping, @Noviny.

Not quite good name tho..

**Comment by Noviny** [comment]
We want to move away from using workspaces as it means too many different things. And then I noticed how ambiguous the new one is. Um. Rename coming soon?

**Comment by tunnckoCore** [comment]
`get-workspaces` is the single best and exact match possible. It's doing exactly what it says, no matter what "workspaces" may mean for different people and things.

It gets the workspaces (`[foo/*, bar/*, packages/*, whatever/*]`) from monorepo, but also gets the packages of each of the workspaces
