### ISSUE TITLE
Discussion: should private packages have changesets/when should you add a changeset?

### ISSUE THREAD

**Issue by mitchellhamilton** [atlassian/changesets#22]
> by private packages I'm referring to packages that aren't published based on the [private package.json field](https://docs.npmjs.com/files/package.json#private), not ones that are published privately

I feel like this has come up a few times and I think it would be nice to have a discussion and come up with an answer that changesets recommends and create a resource that we can point to when other people ask this question.

I used to have the opinion that changesets should only exist when changing something that needs to be released. My opinion has since changed to being "always add a changeset if you're changing a package" because adding a changeset even when it's not strictly necessary doesn't really hurt anything but missing a changeset can be very bad and adding them more often than not reduces the likelihood of accidentally missing a changeset.

I also recall @Noviny talking about how figuring out whether a change is something that needs to be released is more complex than it sounds at some point but I can't explain it well.

cc @timleslie @jesstelford because I think you might have thoughts on this

**Comment by jesstelford** [comment]
Yep, always supporting changsets should be a thing, private or not. The only impact `"private": true` should have is at the publish step, and that's already handled by `npm`/`yarn` 👍

**Comment by Noviny** [comment]
My view is every package should have changelogs - even things that don't end up on npm. It doesn't really cause any harm, but it can help future explorers.

> I also recall @Noviny talking about how figuring out whether a change is something that needs to be released is more complex than it sounds at some point but I can't explain it well.

This is more in relation to what kinds of files changed should cause a release, and may be more relevant in Atlaskit, where things don't get batched very often. Releasing just because you updated types or docs can feel a bit odd, but in AK not adding a changeset for these can lead to un-observed changes causing bugs.

I think my recommendation statement would be:

---
We recommend always adding a changeset, even if you are unsure. If the information ends up not being relevant, it's easy to remove from the changelog later, but it is far harder to recover if the information is never added.
---

Does that sound good to people?

**Comment by 454de6e** [comment]
Let's say I have a monorepo with a couple of packages in `packages/*` and then another package `docs` for the documentation. Everything in `packages/*` follows semantic versioning and gets published to npm, but docs never gets published as package and semantic versioning makes no sense.

How do I go about versioning when I create changesets for the `docs` package? Treat changes always as patches or always as minor?

cc @Noviny, @mitchellhamilton

**Comment by Noviny** [comment]
Hi @454de6e , the way you version it is a little bit flexible, and in large part depends on how much you want to keep track of. It's fine if you wanted to add no changesets, and so never bump the package. I tend to think tracking docs changes is kind of useful. Semver doesn't precisely apply but I would go with:

- patch: fixing words. Typos, tidying sentences for clarity, but not adding to or changing docs
- minor: Adding entire new docs pages or sections
- major: Reworking docs, invalidating an old section, or rewriting it.

With this tracked, it becomes easier to see where you last looked at the docs, and then what the changes have been, to see if you need to update an API.

Another fun thing, if the versions at all relate to your package releases, you can actually publish the docs package, and so make it easy to find docs related to particular versions.
