### ISSUE TITLE
Make custom logo

### ISSUE THREAD

**Issue by Noviny** [atlassian/changesets#299]
## Problem

Currently we are using the apple butterfly emoji as the logo for the project, and while that's nice, I wanted to have a thing that was specifically for this project.

## Proposed solution

I wanted to pick our own butterfly, and get a drawing of it. I had a couple of criteria for it:

1) An Australian butterfly
2) It should be recognisable at-a-glance as not the apple emoji

What I ended up picking was the scarlet jezebel, pictured below.

![The Scarlet Jezebel](https://upload.wikimedia.org/wikipedia/commons/9/9b/584px-Scarlet_jezebel_kobble07trim.JPG)

Things I think we need to use this as our logo:

1) A simple drawing of it in a similar pose to most butterfly emoji, able to be added to readmes
1a) Preferably an svg so we can scale it as needed?
2) A scaled down version that could be used in, say, a website favicon
3) A quick color palette drawn from the butterfly so not-logo things can match it

Editors note: I realised after picking this butterfly that its colours are a little bit warning colours, and maybe this isn't great.

**Comment by Noviny** [comment]
For reasons of not looking like a warning label, we were thinking of using the Papilio ulysses ambiguus Rothschild

![Papilio ulysses ambiguus Rothschild](https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Papilio_ulysses_ambiguus_Rothschild%2C_1895.JPG/1600px-Papilio_ulysses_ambiguus_Rothschild%2C_1895.JPG)

We want it be laid out like the butterfly emoji, but to be distinct enough that you know what it is.

**Comment by Noviny** [comment]
I personally quite like its weird wing blob

**Comment by zkochan** [comment]
maybe make it a butterfly from legos, as you operate with many packages
![image](https://user-images.githubusercontent.com/1927579/79043756-ecf12d00-7c09-11ea-9136-7cfc01bcc44c.png)

**Comment by ianstormtaylor** [comment]
![image](https://user-images.githubusercontent.com/311752/113070995-d6811000-9191-11eb-9ca2-de1b52d2504b.png)

Here's a concept I designed. 

Based on the butterfly but abstracted and simplified, so you can still use the emoji and people will get the connection. I added a few different assets (banner, avatar, logo, icon) to a repository: https://github.com/ianstormtaylor/changesets-logo — happy to transfer it to the `changesets` GitHub organization if you like it.

**Comment by Andarist** [comment]
Wow, that's awesome! I think it could just be added to this repository, in the `assets` directory or smth.

**Comment by mitchellhamilton** [comment]
😍 that looks great! Having it in the changesets org or this repo sounds good to me, whatever is easier for you @ianstormtaylor.

**Comment by ianstormtaylor** [comment]
Thanks! Totally up to you maintainers which way to go. 

Upside to keeping it in the repo is it's all organized in the same place which is nice. Upside to making its own repo is that the asset filesizes can grow without needing to be downloaded, and more logo-specific scripts (like compiling a favicon) don't need to be in the main repo. Either way works. 

(With Prettier they opted to just [transfer the logo to the org as a repo](https://github.com/prettier/prettier-logo), but they weren't necessarily using a monorepo in the first place either. They've since added an animated logo export to the repo as well which is interesting.)

Let me know either one and I can make it happen. For transferring I think [I need permissions](https://docs.github.com/en/github/administering-a-repository/transferring-a-repository#about-repository-transfers) and then I can transfer, or for adding to this repo I could write a PR.

**Comment by Andarist** [comment]
PR works better for me personally. 

Good job on the Prettier logo as well, I've always liked it and didn't know that you are its author ❤️

**Comment by mitchellhamilton** [comment]
Cool, let's do a PR then

**Comment by JounQin** [comment]
It would be great to provide an official badge like the following:

[![changesets](https://img.shields.io/badge/maintained%20with-changesets-176de3.svg)](https://github.com/atlassian/changesets)
