### ISSUE TITLE
Allow Running Custom Commands Per "Lifecycle"

### ISSUE THREAD

**Issue by jbolda** [atlassian/changesets#310]
## Affected Packages

Extent not quite known.

## Problem

We are hoping to use changesets in a polyglot monorepo. We have multiple packages with multiple languages (Rust and js at the current moment.) Obviously we are unable to version, generate changelogs and publish Rust.

## Proposed solution

I believe we could abstract out the commands that are run at the various "lifecycles" and allow them to be configured. We would set the default commands to be the existing functionality for backwards compatibility. This would solve our dilemma as we could run the Rust commands instead which mirror the current functionality. This would also allow other cases such as #171.

This would also allow changesets to expand outside of js-land. With GitHub Actions and the bot, a pure Rust package could use changesets through the automation and never need to install node. A simple script to create the markdown file could be created, or it can be done manually (or strictly through the bot).

If there is interest for this, I would be willing to tackle a PR for it.

**Comment by Noviny** [comment]
This would be awesome and thanks for the interest! It's worth noting that most of the functional bits are abstracted already. The core concepts beyond are:

- write `changeset` files that contain versioning info
- generate a `release plan` out of all changesets currently on disc
- apply a release plan to a repo
- publish (go to each package and run the publish command in it)

I'm not familiar with rust, so not sure what changes you need to make to those lifecycles (beyond targeting packages that don't have a `package.json` for things).

Happy to be a sounding board for this as you experiment.

**Comment by jbolda** [comment]
Great! I think by far the most work will be finding the packages. I would love some thoughts on making that flexible. I think the easy answer is a plugin system, but that seems to be a pretty hefty undertaking.

The versioning and publishing can take a command easy enough (Rust has a `cargo version` crate and standard publishing for example). I imagine the changelog generation is already pretty standard.

Looking forward to making this happen!

**Comment by Noviny** [comment]
> The versioning and publishing can take a command easy enough

We already detect pnpm to run `pnpm publish` over `npm publish` so I don't think this will be too bad.

For getting rust packages, I'd look at [@manypkg/get-packages](https://github.com/Thinkmill/manypkg/tree/master/packages/get-packages) for inspiration. I'd be curious about what extending that to get rust packages looks like, rather than going full plugin just yet.

**Comment by jbolda** [comment]
I think for Rust we would likely just need to find and parse the `Cargo.toml`, so I think it is completely plausible to add it in as an extra "built-in" find. That `@manypkg/get-packages` isn't used in `changesets` currently, correct? I would expect it would show up in `get-workspaces`, but I am not seeing it there.

**Comment by jbolda** [comment]
Well, I am dev on windows and there are a bunch of upstream issues that need to get sorted before I can run tests with any test with real success. I made a little bit of progress, but it is hard to understand what is failing right now.

With the `get-packages`, it looks like it was completely pulled out and uses `@many/get-packages` so I assume I will need to submit a PR there? It seems like it is going to be a pretty big rewrite though, and I assume you want to avoid any breaking changes @Noviny ?

**Comment by zkochan** [comment]
Regarding the issues on Windows. Most of the issues are due to an issue in jest-fixtures (https://github.com/atlassian/changesets/issues/329#issuecomment-615260265). Also there is one failing test due to this issue: #309. The rest were fixed in this PR: #331

**Comment by Noviny** [comment]
I’m not against breaking changes, though @mitchellhamilton probably has opinions on it. If you have a separate ‘get-rust-packages’ lib, I’m happy to use that and combine our packages list (adding a type(?) field to it so it can be auctioned properly.

It makes more sense to rewrite ‘get-packages’ to me as its goal is to be a very tool-agnostic approach.

**Comment by jbolda** [comment]
Thanks @zkochan, I saw your PR yesterday and was hopeful, but it seems that jest-fixtures has been sitting out there for some time. I wonder if it is worth adding windows to the CircleCI setup to keep parity in the future.

I imagine any `get-rust-packages` or equivalent for other languages would be implemented in their own specific language. `get-packages` is very much tied to a `packageJson` and removing that would likely be a breaking change. We could possibly have a list of package managers and a list of package files / languages. The default set would be `js` for now to avoid breaking changes and then one could opt into other packages. We could opt in within `changesets` for now. Then whenever next breaking change happens the default could be switched to any of the built in packages.

**Comment by Noviny** [comment]
a) happy to add windows to circleCI

b) I've asked the owner of `jest-fixtures` about it - if we can't get that published by the end of the week, I'm going to publish a fork for use here.

c) Since they probably want to be their own language, I would guess the best option is implement `get-rust-packages` and then once we've got that, merging it back into `get-packages` can be a later step (which I would like to do).

**Comment by jbolda** [comment]
c) I am perfectly comfortable just implementing directly in `get-packages`. My point with `get-rust-packages` is that I can find any existing `js` library that can do that (or similar for other languages), and I assume the reason why is that the implementation would be in their own language, e.g. Rust would be done in Rust, etc.

I will see what I can do to rewrite `get-packages` to be more agnostic, but where it is currently opt in only.

**Comment by mitchellhamilton** [comment]
> jest-fixtures

Not sure if fixturez has the same problem but a better solution is probably to convert any places where we still use jest-fixtures to fixturez

**Comment by jbolda** [comment]
I think `get-packages` is using `fixturez`, correct? I don't believe I ran into issues with it so that might be the best solution.

**Comment by ryaninvents** [comment]
In the short term, here's what I'm thinking I'll run for my monorepos in CI (someone correct me if I'm wrong here):

1. Dump changeset status to a _/tmp/changes.json_ file with `yarn changeset status --verbose --output=changes.json`
2. Run `yarn changeset version` to bump all _package.json_ versions and perform the git commit (I'm okay with using _package.json_ for my non-Node projects, it won't matter)
3. Build and test each package as before
4. Read in _/tmp/changes.json_ and iterate over `changes.releases`. I would probably use a Gulpfile for this, because I'm familiar with it, but you could use any Bash script or CI configuration.
    - If a package will be published to npm, run `npm publish` from the package directory.
    - For non-npm artifacts, (Docker images, S3 artifacts, etc.), run the custom script. We have access to [version info](https://github.com/atlassian/changesets/blob/01625475252abd3d1e2a0fabceb0e11289c29b40/packages/types/src/index.ts#L37-L41) so it's easy to create Docker tags, S3 paths, etc.
    - For all packages and artifacts, add `git tag -a ${packageName}@${newVersion} -m "Publish ${packageName}@${newVersion}"`. Could possibly attach changelog info as metadata to the tag as well here.
        - I would only want to add the tag _after_ publish in case something went wrong. `semantic-release` will sometimes add the tag to the repo anyways for failed publishes, and I want to avoid that.
5. Read _/tmp/changes.json_ again. If `changes.releases.length > 0`, then something was published. Push the new commit and git tags back to the repo with `git push --follow-tags`.

Since it's pretty formulaic, I might create my own utility for steps 1, 3, 5.

**Comment by Andarist** [comment]
@ryaninvents The described flow seems OK to me 👍

**Comment by jbolda** [comment]
@ryaninvents interested in helping out with my PR? I plan to work on the `get-packages` first if you are interested in pushing #333 forward. We could make a branch or perhaps merge commit on a separate PR.

**Comment by ryaninvents** [comment]
@jbolda I'd like to. I'm busy this week with selling my house, so I probably won't be able to write much code, but I'll take a look as soon as I can.

**Comment by ryaninvents** [comment]
I've published a `0.1.0` release of a package [@ryaninvents/changeset-run](https://www.npmjs.com/package/@ryaninvents/changeset-run) which takes the modular approach I've described above. Please feel free to install it and provide feedback; I know there are probably some issues, but the overall idea seems to work.

**Comment by mitchellhamilton** [comment]
Hey folks, sorry to do after all this work has been put in but @Noviny and I have talked about this and we don't think that building support for Rust/this sort of extensibility in general into Changesets is best for the project.

The reasoning being that it creates _so many questions that we don't want to have to answer_(e.g. what happens if there's a Rust package and a JS package with the same name? What happens if there's a dependency between a JS and a Rust package? How does updating dependents work with Rust packages?) and the problem with that isn't about finding answers to these questions, it's that adding Rust support means that _we have to answer these questions_ where _we previously didn't_ and even if we did answer all these questions and the others that would come up, Rust support constrains what we can do in the future and right now, our primary goal with Changesets is to provide a great experience for versioning JS monorepos and if we are trying to support Rust as well, we won't be able to spend as much time on supporting JS monorepos so we'll have a worse project. We definitely should be clearer about this in our documentation though.

With all that said, if Changesets can help people manage Rust packages as well without constraining Changesets, that's great! So what that means is that, for now, the best solution is going to be @ryaninvents approach of building on top of Changesets and potentially sometime in the future when all the behaviour is figured out, it might make sense to move it into Changesets itself(though this is very much a maybe thing though, we don't believe building support into Changesets itself isn't an inherently good thing). There are also a bunch of ways you could improve this outside of Changesets like generating the package.jsons for Rust packages and etc.

> I should also note that when I'm referring to Changesets here, I'm referring to Changesets-the-tool rather than Changesets-the-idea, Changesets-the-idea is definitely something that transcends a particular language ecosystem though Changesets-the-tool, for now, isn't.

**Comment by JakeGinnivan** [comment]
@ryaninvents's approach seems pretty nice. It would be awesome to have in built support for this.

Basically config to run custom commands instead of NPM publish. I would love to use changesets to control my infrastructure deployments as well as npm package publishes.

**Comment by jbolda** [comment]
@JakeGinnivan I've created a library with polyglot support and arbitrary commands as similarly described here. It sounds like it would applicable to your use case. Happy to discuss further and always love code/docs help. /cc @ryaninvents 

https://github.com/jbolda/covector

I am going to close this as it will not be a supported use case in changesets.

**Comment by JakeGinnivan** [comment]
Thanks @jbolda 

I completely understand the move to not supporting packages from another ecosystem and leaving this as an NPM only tool, I think there is a way that could add the extensibility to changesets itself without it being polyglot.

If package.json is the manifest, currently libraries which are not published to NPM are marked as private. That works.

You *could* add

```
changesets: {
   publish: "my custom publish command"
}
```

To package.json, giving an execution hook and leave everything else the same. For Rust packages you could copy the version number from package.json into the rust manifest, docker could pick the tag up in the same way. For deployment projects (I'm using Pulumi) I can simply run `pulumi up -y` in the custom publish hook and changesets could run it instead of NPM publish.

That way you open up allowing all sorts of possibilities without extending the scope of changesets.
