### ISSUE TITLE
Config method return types are typed as any

### ISSUE THREAD

**Issue by Blasz** [atlassian/changesets#319]
## Affected Packages

@changesets/config

## Problem

The return types for the read/parse methods of @changesets/config are typed as any in the declaration file (https://unpkg.com/browse/@changesets/config@1.0.2/dist/declarations/src/index.d.ts).

## Proposed solution

Properly type them. They are typed in the source files but not in the output for some reason.

**Comment by Andarist** [comment]
@mitchellhamilton this happens because preconstruct removes `dist` directories before the build (which is good) but it means that during build `dist` doesn't exist and TS can't find referenced types from other packages (`@changesets/types` in this situation) and thus it just puts `any` in place of those referenced types. The possible solution would be to build packages in topological order (so dependencies are always built before dependents). I guess there are already utils for building a dependency graph so this would be a matter of sorting and queuing builds appropriately. The same algorithm could be used to also fix this - https://github.com/atlassian/changesets/issues/238
