### ISSUE TITLE
GitHub integration for doing releases

### ISSUE THREAD

**Issue by mitchellhamilton** [atlassian/changesets#44]
Let's say I'm a maintainer of a project that I'm not always able to spend time on and when I can, I merge a bunch of PRs and I want to do a release but the amount of work(while not that big) I have to do is annoying and I think it could be better. Another constraint that I also want to add is that doing a release should still be an explicit action by a maintainer or at least that should be an option.

How do I think this could be solved?

The first part of it is having a bot that runs `changeset bump` on the repo and opens a PR with that whenever there are changesets in master and when changesets are added to master, it resets the old content, runs `changeset bump` and pushes again.

The second part is automating running `changeset release` on master, I think this will require quite a bit of thought because exposing npm credentials would be really really bad.

So with these two things, a maintainer can do a release by hitting the merge button on a PR and everything else will be automatic.

I'm probably going to experiment with this at some point, probably with GitHub actions but I wanted to open this in case there are any big problems with this that I can't see.

**Comment by Noviny** [comment]
>  it resets the old content, runs changeset bump and pushes again.

Really like this as a solution to automating the bump process - it being a bit clunky has been annoying me (the number of round trips you need to make)

>  exposing npm credentials would be really really bad

Someone had a moderately okay solution to this which basically ferried the 2fa request to a slack bot and then back when you run release. Changesets would need to support post-hoc 2fa entry though (working on it).

This keeps 2fa while still having mostly-automated releases.

Maybe this doesn't help because it adds another step.

This is a good idea, and effectively what we do in Atlaskit. The always-around new-release branch helps out a lot (if all I got was that and still had to merge, pull, publish, I would be significantly happier with my life).

You may want to lock down who can merge the release branch further, but that's an easy implementation detail.

**Comment by Noviny** [comment]
This has been done by https://github.com/changesets/action - closing
