### ISSUE TITLE
Add version diff link and date in the changelog version headlines

### ISSUE THREAD

**Issue by daKmoR** [atlassian/changesets#480]
We did use conventional commits before and it created version headlines like so

```
# [1.0.0](https://github.com/open-wc/open-wc/compare/@import-maps/resolve@0.3.2...@import-maps/resolve@1.0.0) (2020-08-19)
```

We now switched to changeset and we really enjoy using it however the changelog lost some nice information as now the version is "just" a static text.

```
## 1.0.1
```

Would it be possible to add the diff link and date to the headline?

**Comment by Andarist** [comment]
It's totally possible but you would have to implement your own changelog generator. An example in the wild:
https://github.com/FormidableLabs/urql/blob/85a0946ed83559988b228a605df0b26e49d40c51/.changeset/config.json#L3
https://github.com/FormidableLabs/urql/blob/85a0946ed83559988b228a605df0b26e49d40c51/scripts/changesets/changelog.js

Keep in mind that you probably wouldn't have to reimplement the whole thing - you could totally reuse the ones we provide and just adjust the outcome a little bit before returning from your custom one.

Also, keep in mind that the generated date won't match the release date because changelog generation are independent processes - unless you do both manually without our github action etc.

**Comment by daKmoR** [comment]
sweet 🤗

thank you 🙇‍♂️
