### ISSUE TITLE
Changeset version not working due to wrong dependency range

### ISSUE THREAD

**Issue by adriencohen** [atlassian/changesets#532]
## Affected Packages

`pkg:apply-release-plan`

## Problem

`changeset version` command returns `🦋  error TypeError: git.getCommitsThatAddFiles is not a function`

With the following resolution in yarn.lock:

```
"@changesets/apply-release-plan@npm:^4.2.0":
  version: 4.2.0
"@changesets/git@npm:^1.0.5":
  version: 1.0.6
```

## Proposed solution

With a clean install I don't have the issue I think this is related to [@changesets/git 1.1.0](https://github.com/atlassian/changesets/blob/bcf0f7ed0c6c2becb507fc646f1fc2c1638ba01d/packages/git/CHANGELOG.md#110) where `getCommitsThatAddFiles` was added. The version of this package was not bumped in `@changesets/apply-release-plan`  package.json even though it's using this function

If I'm right in the package.json of `@changesets/apply-release-plan` we should have `"@changesets/git": "^1.1.0",`

**Comment by Andarist** [comment]
You are right - the PR that has introduced those changes did not contain a changeset for the `@changesets/apply-release-plan`: https://github.com/atlassian/changesets/pull/495/files . I guess this is partially caused by our releasing strategy that attempts to minimize required releases - I will be working on an alternative strategy in the following weeks that should not allow this to happen.

Would you like to prepare a PR fixing this?
