### ISSUE TITLE
[Question] when are downstream packages bumped

### ISSUE THREAD

**Issue by tpluscode** [atlassian/changesets#544]
Looking at myself current project state, I have to packages

| pkg | version |
| -- | -- |
| `@cube-creator/core-api` | `0.3.1` |
| `@cube-creator/shared-dimensions-api` | `0.3.0` |

`core-api` has a dependency on the other one.

In the [current release PR](https://github.com/zazuko/cube-creator/pull/617), the `shared-dimensions-api` package gets a patch bump. Why isn't there an "Updated dependencies" change and a bump of the downstream package, like for example in an [earlier release](https://github.com/zazuko/cube-creator/pull/588)

**Comment by Andarist** [comment]
Because `@cube-creator/core-api` is not part of this release and the dependency range that it has defined for `@cube-creator/shared-dimensions-api` is satisfied:
https://github.com/zazuko/cube-creator/blob/044a33b9b7089d5fcb4031795673a103141f37f0/apis/core/package.json#L12

In a sense - there is no reason to generate a release for it.

This tends to be confusing at times and because we all are just humans and Changesets are only semi-automated and still rely on us, humans, quite a bit we are thinking about introducing a new option that would switch the project to a different bumping strategy: https://github.com/atlassian/changesets/pull/542

**Comment by tpluscode** [comment]
Thanks. I see how the range makes sense if they were both packages deployed to NPM but, despite the confusing name, the `core-api` package is in fact the final app (there should be a third one, purely to combine two APIs but the principle remains).

Thus, if I don't bump the downstream, I will not get a docker build triggered...

**Comment by tpluscode** [comment]
Great, got it. Thanks!
