### ISSUE TITLE
Customise how .changeset/*.md files are created

### ISSUE THREAD

**Issue by airtonix** [atlassian/changesets#551]
## Affected Packages

not really sure? `cli`, `write` ? 

## Problem

We need the changeset files created by our developers to automatically have the jira ticket instead of the git commit.

right now the changeset file looks like: 

```
---
'@ourthing/fastlane': patch
---

Fastlane can now handle android flavours and will now deploy to internal track.
```

But since we have a branch naming convention enforced, I'd like to capture that when the above file is created: 

```
~/Projects/our-thing fix/UI-12345-a-thing
> yarn changeset
...
```
I'd want the changset file created to look more like this (actually I want the freedom to make it look however I want)

```
---
'@ourthing/fastlane': patch
---

[UI-12345] Fastlane can now handle android flavours and will now deploy to internal track.
```

## Proposed solution

probably the least effort/most correct is that the config exposes:

```
{
  "$schema": "https://unpkg.com/@changesets/config@1.5.0/schema.json",
  "changelog": "@ourthing/changelog-formatter",
  "changeset": "@ourthing/changeset-formatter",                  <---- that
  "commit": true,
  "linked": [],
  "access": "restricted",
  "baseBranch": "develop",
  "updateInternalDependencies": "patch",
  "ignore": []
}

```

Then we are free to write our own logic that modifies data provided to `@changesets/write`

**Comment by mitchellhamilton** [comment]
This isn't really something that we would want to do. Currently the only place that we run user code is when generating the changelogs, this is really useful because we can have tools like the GitHub bot that can create changesets, see what the new versions are and etc. Also, this wouldn't really enforce it since someone could manually create a changeset without going through the CLI. If you want to achieve similar behavior, you could have some check to enforce that the Jira ticket is in the changeset or if the Jira ticket will be in the commit, get the Jira ticket from the commit in the changelog generator.
