### ISSUE TITLE
include --open flag on add command?

### ISSUE THREAD

**Issue by ianstormtaylor** [atlassian/changesets#554]
## Affected Packages

`pkg:cli`

## Problem

Sometimes you want to just edit the changeset by hand instead of using the prompts, so you use `--empty`. But then you have to manually go find the right filename that was just created. It would be nice to be able to open it automatically with the default editor.

## Proposed solution

Potentially as an `--open` flag.

**Comment by Andarist** [comment]
Right - we support opening the external editor when using prompts (have you used it?) but I think we've missed adding this for the `--empty` case. I will try to work on adding this 🔜 (-ish)

**Comment by ianstormtaylor** [comment]
@Andarist I tried doing that but it seems like the "submit empty line to open external editor" functionality might be broken. It opened an external editor but then didn't do anything when I typed, saved, and closed it.

**Comment by Andarist** [comment]
@ianstormtaylor you could create a new issue about this but this might be very specific to your external editor, its settings etc. So actually it would be great if you could try to debug this on your machine. I would check this this synchronous/blocking `edit` call resolves in your case:
https://github.com/atlassian/changesets/blob/5b6005e0349a105b3d138fccdb22d13de8949862/packages/cli/src/utils/cli-utilities.ts#L90-L91

We had some issues with the logic running into an infinite loop because of some auto-save configurations in editors so we had to do this for the time being: https://github.com/atlassian/changesets/pull/518/files

**Comment by ianstormtaylor** [comment]
@Andarist thank you! That helped to debug the issue. For future folks, my `.bashrc` was:

```
export EDITOR=code
```

But it should instead be:

```
export EDITOR="code --wait"
```

I hadn't noticed before because git uses the editor from its internal config and it was correct there.
