### ISSUE TITLE
patch+minor changesets resulting in major version bump

### ISSUE THREAD

**Issue by ianstormtaylor** [atlassian/changesets#555]
## Affected Packages

`pkg:cli`

## Problem

Somehow `minor` changes are resulting in a major version bump. If you look at the PR being updated at: https://github.com/ianstormtaylor/slate/pull/4156 — prior to adding a few `minor` changesets it was correctly putting the next versions at `0.61.4`, but now it says `1.0.0` despite no changesets listing `major` changes. 

I'm worried to merge it now for what it will do.

---

Edit: I think this may be similar to https://github.com/atlassian/changesets/issues/524, but I don't quite understand exactly what is going on here in the first place.

**Comment by ianstormtaylor** [comment]
Adding the experimental `onlyUpdatePeerDependentsWhenOutOfRange` did fix it. Still not exactly sure why, but at least it works!

**Comment by Andarist** [comment]
Im on mobile and its 5am so i cant confirm in full - but yes, probably the reason is the same as in other issue.

At the beginning Changesets wanted to play safe - lifting the some burden from the users but it turns out that this is just not what people expect (hence the extra unsafe flag that might become the default or smth in the next major version)

Imagine this:
1. Add a feature to your pkg which is a peer dep
2. Dont use it yet in a dependant
3. After some months start using it
4. Locally it works - tests run against the latest versions of your packages
5. The next release is broken for your consumers since u forgot to bump the peer dep range

From what I understand this is reasoning behind this behavior but i was not around when it was introduced so i might also miss some context

**Comment by BeeeQueue** [comment]
Would it be possible to add a setting to only bump the version a patch version rather than either a major version or none at all?

**Comment by Andarist** [comment]
@BeeeQueue Isn't this exactly what `onlyUpdatePeerDependentsWhenOutOfRange` is about?

**Comment by BeeeQueue** [comment]
No, I mean only bumping by a patch version rather than either a major version (or nothing at all, which that options does from my testing)

**Comment by Andarist** [comment]
@BeeeQueue could you provide a changeset config, input package.json files, and the diff result of running `changeset version`? That would get us on the same page quickly.

**Comment by BeeeQueue** [comment]
https://github.com/BeeeQueue/changesets-peer-versions/commits/main

The last 2 commits are the ones in question.

- Minor changeset is added
- Package with it as peer dependency is bumped a major version

Usually we know when we use a new feature in the dependent package and can manually bump that package at the same time, but if we know we don't use the new feature (the change will not be breaking) we cannot _not_ bump it a major version.

**Comment by Andarist** [comment]
If the contract is satisfied (you don't use any new features of your peer dependency) then why would you like to bump the peer dependant with a patch? It doesn't require it. 

How I see it you have only two possible situations here:
- either the peer dependency contract is still satisfied
- or it's not

The first one doesn't require any bump while the latter requires a major. Could you go into more detail how those two situations don't cover all scenarios?

**Comment by alcuadrado** [comment]
Doesn't npm7, which is aware of peer dependencies, make not bumping the dependent to a new major more reasonable? If an in-range update is required, npm will do it.

This is still very fuzzy in my mind to be honest, as it depends on how the user declared/installed the peer dependency. It works with a caret, may not work for others.
