### ISSUE TITLE
Create git tags during version instead of publish

### ISSUE THREAD

**Issue by joeldenning** [atlassian/changesets#612]
## Affected Packages

`@changesets/assemble-release-plan`
`@changesets/apply-release-plan`

## Problem

For the https://github.com/single-spa/create-single-spa monorepo, I use `changeset version` but use `pnpm publish -r` rather than `changeset publish`, as encouraged by https://pnpm.io/using-changesets.

The problem is that no git tags are created with those two commands:

| command | creates git tags? |
| --------- | ----------------- |
| `changeset version` | ❌  |
| `changeset publish` | ✅  |
| `pnpm version` | ✅  |
| `pnpm publish` | ❌  |

My ideal would be creating a separate git tag for each package in the monorepo - for example `webpack-config-single-spa@3.1.0` and `webpack-config-single-spa-react@2.1.0`

I first proposed a change to pnpm publish, but they thought the best place to implement the tagging would be during changeset version (see https://github.com/pnpm/pnpm/issues/3586).

### Option 1

Add a new flag `changeset version --git-tag` that commits and creates git tags. This would more closely match npm, yarn, and pnpm, all of which create git tags during their respective `version` commands.

### Option 2

Add a new command `changeset tag` that can be executed after `changeset version` and commit are completed, as an alternative to `changeset publish` for those using pnpm to publish rather than changeset

**Comment by DavidWells** [comment]
Did anyone figure out how to make this work? 

I'd use `changeset publish` but I'm running into this `JSON.parse` issue described here https://github.com/atlassian/changesets/issues/397#issuecomment-897264441 

Publishing works with `pnpm publish` but no tags are setup like mentioned here.

**Comment by joeldenning** [comment]
I haven't figured out a workaround for this.

**Comment by zoubingwu** [comment]
I am using pnpm too and planning to automate this release process in my project. 

@joeldenning Do you publish from you local machine instead of using ci? Will adding a script to read package name/version and tagging it be enough to solve this issue?

**Comment by Andarist** [comment]
I think option 2 makes sense here. If anybody would like to contribute this - I would gladly merge a PR with this. 

I would also appreciate it if you could describe how you would like to utilize changesets in your workflow. Assuming our default workflow, including a flag for `version` doesn't make a lot of sense to me because versioning usually happens even days before publish - so tagging at that moment in time would be incorrect if those tags would get published to the remote at that moment. From what I understand you are mostly interested in tagging as part of the publishing process - it's just that you are not using `changeset publish` but an alternative script.

**Comment by joeldenning** [comment]
I had some time today so I implemented this in #634
