### ISSUE TITLE
Issues with usage around updateInternalDependencies config option

### ISSUE THREAD

**Issue by akshayr20** [atlassian/changesets#649]
## Affected Packages

Hi Team, thanks for your great work on this project.
I am facing some challenges in correctly configuring changesets, now I am not sure either its a bug or invalid configuration.

As per the [documentations](https://github.com/atlassian/changesets/blob/main/docs/config-file-options.md#updateinternaldependencies)  to manage dependent package versioning we are using updateInternalDependencies option. (updateInternalDependencies: patch)

Assume there are two  packages `pkg-a @version 1.0.0` and `pkg-b @version 1.0.0`  

`pkg-b` is dependent on `pkg-a`

After adding a **patch version** of `pkg-a`, `pkg-b` gets auto-updated to a patch version (**desired flow:** works correctly)

## Problem

After adding a **minor version** of `pkg-a`, `pkb-b` get auto-updated to a major version (**desired flow:** should be updated to a minor version)

If you could guide me around same it would be really helpful.

**Comment by akshayr20** [comment]
Thats correct, its a peer dependency

**Comment by Andarist** [comment]
For the time being, u can use a config flag like here:
https://github.com/statelyai/xstate/blob/5a0dd8d1196d44badbb371c3dfcc82c6abcfb7ce/.changeset/config.json#L17-L19

The idea was that within a monorepo it's easy to forget that your consumers might depend on an older version of your package - since it's a peer dep. So the current behavior guards you against breaking the contract with them. However, in practice, this makes you bump major versions of packages way more often than you'd like. It's hard to strike a balance between both of those goals here (minimizing majors and making it safe for consumers) but we are going to have to reconsider how this works in the next major version and see if we have any alternatives.
