### ISSUE TITLE
Fix messaging for single-package changelog generation

### ISSUE THREAD

**Issue by Noviny** [atlassian/changesets#98]
Currently, you get asked 'which of these packages is major/minor?' and select it

Single package should have slightly modified workflow to be 'should this package be bumped as a major/minor' as a boolean option.

Thanks [💯💜🎉](https://github.com/Noviny/emoji-uid) for revealing this problem.

**Comment by chasemccoy** [comment]
@Noviny This is definitely the only thing preventing my team from adopting changesets for our component library! The flow now (where you have to search through a list of 1 package for each version type) is awkward when you only have 1 package, so much so that the first time I went through this flow I didn't know how to proceed (I was trying to arrow up/down to select, and it took me forever to figure out that it was a search box).
